// This file is automatically generated. Do not edit it directly.
//
// Singleton Supabase client used by every component/hook for direct table
// reads and Realtime subscriptions. Uses the public anon key — safe to
// expose client-side, since RLS policies on each table (see
// supabase/migrations) are what actually govern what anon can do. The
// anti-cheat score-writing paths bypass this client entirely and call the
// memory-game/snake-game edge functions instead, which write with the
// service-role key.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});